---
title: "Rust错误处理"
categories: "Rust"
---

*每个人都会犯错，编程业务也不例外，有些错误可以挽回，有些则不可以挽回*
编程中有两种错误，一种错误可以捕捉并处理，另外一种则导致程序崩溃

在Rust语言中，把错误分成两大类：可恢复与不可恢复

- 可恢复的错误，如读取不存在的文件，并不会导致程序无法继续执行，抛出错误即可
- 不可恢复的错误，如内存越界，将导致程序异常结束
### 可恢复错误
与**可恢复错误**对应的是Result枚举，定义如下：
```
enum Result<T,E>{
	OK(T),
	Err(E)
}
```
其中T，E是**泛型参数**，也即，可以是任意类型

- T用于表示Result的值为OK时的返回值 
- E用于表示Result的值为Err时的返回值 

这两个泛型参数的作用是携带成功执行的结果或失败的错误信息
下面是一些例子
- 打开一个不存在的文件
```rust
use std:fs:File
fn main(){
	// open函数返回Result类型
	//假设该文件不存在
	let f = File::open("main.md"); 
	//格式化输出调试信息
	println!("{:?}",f);
}
```
以上代码的输出结果如下,可以看到，f的值为Err类型，正是Result的泛型参数Err
```
Err(Error { repr: Os { code: 2, message: "No such file or directory" } })
```
- 在现实中，我们不可能像上面一样不对错误进行处理，我们使用`match`对Result的不同值进行处理
```rust
fn main(){
   let result = is_even(13);
   match result {
      Ok(d)=>{
         println!("no is even {}",d);
      },
      Err(msg)=>{
         println!("Error msg is {}",msg);
      }
   }
   println!("end of main");
}
fn is_even(no:i32)->Result<bool,String> {
   if no%2==0 {
      return Ok(true);
   } else {
      return Err("NOT_AN_EVEN".to_string());
   }
}
```
以上代码的输出结果如下
```
Error msg is NOT_AN_EVEN
end of main
```
对于一个Result类型，如果没有使用，编译器会给出警告
> 注意，对于可恢复错误，程序会在错误处理后继续执行。Result枚举封装了正常返回的值和错误信息，带来的好处是只用一个变量就能接受正常值和错误信息，不会污染全局空间

### 不可恢复错误
与**不可恢复错误**对应的是panic!()宏，他会将特定的错误信息输出，并结束程序
当遇到不可恢复错误时，程序会自动调用`panic！()`;我们也可以手动调用退出程序
> 除非是不可挽救的错误，不要手动调用panic!()

### unwrap()和expect()函数
以上Result的例子使用match函数进行处理，为了让代码更加简洁，诞生了这两个错误处理函数

这两个函数服务于Result和Option类型
- `unwrap(self):T`
- `expect(self,msg:&str):T`
这两个函数几乎一样，当self是Ok或some时，则返回包含的值，否则，前者直接调用panic!()宏退出程序；后者输出错误信息str并退出程序

#### 代码示例
等同于以上match的例子，is_even(10)的返回值作为unwrap()的参数
```rust
let result = is_even(10).unwrap();
```

expect（）代码示例
```rust
 let f = File::open("pqr.txt").expect("File not able to open");
```

